### ISSUE TITLE
Enhance Disads to support a Fedora R-Datastream

### ISSUE THREAD

**Issue by msuhovec** [ndlib/disadis#3]
Eventually, Disadis will be redirected by Fedora (The Redirect Datastream type) to redirect to server content from Bendo. It needs to handle that.

**Comment by dbrower** [comment]
This seems to be working in staging as-is. There were a few bumps:
* bendo was not returning a content-length, which disadis requires (fixed in ndlib/bendo#97)
* disadis pulls the mime-type from the response. Because of the R datastream, it will pull the content-type from bendo (which is using an [algorithm](https://golang.org/pkg/net/http/#DetectContentType) in the go std library to sniff mime types) instead of using the content-type stored with the fedora datastream. There will probably be differences. This might cause problems.
